#!/bin/bash

# Import our utility functions
. $(dirname ${BASH_SOURCE[0]})/bin/utils.sh
. $(dirname ${BASH_SOURCE[0]})/bin/build

trap UnsetUtils EXIT

RequireDocker
PermissionsCheck

_QI_POSITIONALS=()
while [[ $# -gt 0 ]]; do
    __qi_arg="$1"
    case $__qi_arg in
        -w|--workspace)
            __qi_workspace=$(GetAbsPath "$2")
            shift; shift
        ;;
        -d|--datasource)
            __qi_datasource=$(GetAbsPath "$2")
            shift; shift
        ;;
        -p|--provider)
            __qi_provider="$2"
            CheckProvider "$__qi_provider"
            shift; shift
        ;;
        -t|--template)
            __qi_template=$(GetAbsPath "$2")
            shift; shift
        ;;
        *) # Unkown options
            _QI_POSITIONALS+=("$1")
            shift
        ;;
    esac
done
set -- _QI_POSITIONALS

CheckWorkspace "$__qi_workspace"
CheckDataSource "$__qi_datasource" "$__qi_workspace"

if ! [ $# -ge 3 ]; then
    echo "USE: ${BASH_SOURCE[0]} <WORKSPACE> <DATA> <PROVIDER> [TEMPLATE]" 1>&2
    exit 1
fi

__qi_application_name=$(GetContainerName "qi-c" "$__qi_provider")

function finish()
{
    unset __qi_application_name
    unset __qi_datasource
    unset __qi_provider
    unset __qi_workspace

    unset -f finish
}

trap finish EXIT

GetBuilder

Build \
    "$__qi_workspace" \
    "$__qi_application_name" \
    "$__qi_template"

if ! [ -z "$__qi_template" ]; then
    __qi_application_name=${__qi_application_name}-${__qi_template##*.}
fi

. $(dirname ${BASH_SOURCE[0]})/bin/deploy \
    ${__qi_application_name} \
    ${__qi_provider} \
    ${__qi_datasource}

if ! typeset -f ConnectToServer >/dev/null; then
    echo "An error occurred during deployment and no Jupyter server was found." >&2
    exit 1
fi

if [ ! -z ${__qi_provider/local/} ]; then
    echo
    echo "*** USE THE FOLLOWING URL TO CONNECT TO YOUR JUPYTER SERVER ***"
    echo ${JUPYTER_SERVER}:8888
    echo
    read -n 1 -p "PRESS ENTER TO CONTINUE AND RETRIEVE YOUR TOKEN" input
    echo

    trap \
        'echo "\nTerminating connection to host. Server will continue running remotely"' SIGINT
fi

ConnectToServer
