FROM nvidia/cuda:9.0-cudnn7-runtime as GPU_BASE
FROM {% APPLICATION %}

COPY --from=GPU_BASE /usr/local/cuda-9.0/ /usr/local/cuda-9.0/
COPY --from=GPU_BASE /var/lib/dpkg/info/cuda* /var/lib/dpkg/info/
COPY --from=GPU_BASE /etc/apt/sources.list.d/cuda.list /etc/apt/sources.list.d/cuda.list
COPY --from=GPU_BASE /etc/ld.so.conf.d/cuda-9-0.conf /etc/ld.so.conf.d/cuda-9-0.conf

ENV NB_USER=$USER
USER root
RUN ln -s -T /usr/local/cuda-9.0 /usr/local/cuda
USER ${NB_USER}
